title: "Библиотека AI-промптов"
description: "Структурированная коллекция промптов для различных AI-моделей"
baseurl: ""
url: "https://yourusername.github.io"

collections:
  prompts:
    output: true
    permalink: /:collection/:name/

defaults:
  - scope:
      path: ""
      type: "prompts"
    values:
      layout: "prompt"
